---

- name: Deploy Docker Wordpress 
  hosts: all
  vars:
    freenom_domain: umblertest.tk
    certbot_email: viniciusbmello@gmail.com
  roles: 
   #- change_ssh_port
    - set_timezone
    - update_debian_like
    - install_aptitude
    - install_docker_compose
    - compose_directories
    - deploy_wordpress_http
    - certbot_force_renewal
    - enable_https_nginx

...
