---

- name: Deploy Docker Wordpress 
  hosts: all
  vars:
    freenom_domain: umblerchallange.tk
    certbot_email: viniciusbmello@gmail.com
  roles: 
    - allow_iptables_input
    - set_timezone
    - update_debian_like
    - install_aptitude
    - install_docker_compose
    - compose_directories
    - deploy_wordpress_http
    - certbot_force_renewal
    - enable_https_nginx
    - deny_iptables_input

...
