---

# update_debian_like

- name: Update target operating system (Debian like)
  apt:
    upgrade: yes
    update_cache: yes
  when: (ansible_distribution == 'Debian') or
        (ansible_distribution == 'Ubuntu')

...
